//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace newsoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public int subcategoryID { get; set; }

        [Required]
        public string title { get; set; }

        [Required]
        public string shortdesc { get; set; }

        [AllowHtml]
        public string content { get; set; }

        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
    
        public virtual Subcategory Subcategory { get; set; }
    }
}
